name: Update Socials JSON

on:
  schedule:
    - cron: "0 7 * * *" # Runs daily at 7am UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Rebuild .env from secrets
        run: |
          echo "GOOGLE_SERVICE_ACCOUNT_EMAIL=${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}" >> .env
          echo "GOOGLE_SHEET_ID=${{ secrets.GOOGLE_SHEET_ID }}" >> .env
          echo "GOOGLE_PRIVATE_KEY_B64=${{ secrets.GOOGLE_PRIVATE_KEY_B64 }}" >> .env

      - name: Run fetch script
        run: node scripts/fetchSocials.js

      - name: Commit and push updated socials.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git pull --rebase origin main
          git add public/data/socials.json
          git commit -m "Update socials.json [auto]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
