name: Update Google Reviews

on:
  schedule:
    - cron: "0 6 * * *" # 6am UTC daily
  workflow_dispatch:

jobs:
  update-reviews:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Rebuild .env from GitHub Secrets
        run: |
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> .env
          echo "GOOGLE_PLACE_ID=${{ secrets.GOOGLE_PLACE_ID }}" >> .env

      - name: Install dependencies
        run: npm ci

      - name: Run review fetch script
        run: node scripts/updateReviews.js

      - name: Commit and push reviews.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add public/data/reviews.json
          git commit -m "Update reviews.json [auto]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
